name: refresh

on:
  workflow_dispatch:
    inputs:
      deploydir:
        description: 'file(s) directory'
        required: true 
        type: string
        default: 'preset-lede'
      dotconfig:
        description: '<serial>.config file(s)'
        required: true 
        type: string
        default: '1.config, 2.config'

permissions:
  contents: write

jobs:

  set-matrix:
    runs-on: ubuntu-latest
    outputs:
      dotconfig: ${{ steps.set-matrix.outputs.dotconfig }}
      deploydir: ${{ steps.set-matrix.outputs.deploydir }}
    steps:

      - uses: actions/checkout@v3
      
      - id: set-matrix        
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            let dotconfig = [];
            let cLs = "${{ inputs.dotconfig }}".replaceAll(' ', '').split(',');
            let deploydir = "${{ inputs.deploydir }}".trim();
            if (deploydir.endsWith('/')) deploydir = deploydir.slice(0, -1);
            for (i=0; i<cLs.length; i++) {
                try {
                    fs.accessSync(deploydir + '/' + cLs[i]);
                    dotconfig.push(cLs[i]);
                }
                catch (err) {
                    console.log(cLs[i] + ' does not exist!');
                }
            }
            core.setOutput("dotconfig", JSON.stringify(dotconfig));
            core.setOutput("deploydir", deploydir);

  refresh:
    needs: set-matrix
    runs-on: ubuntu-latest
    env:
      DEPLOYDIR: ${{ needs.set-matrix.outputs.deploydir }}
      FILE: ${{ matrix.file }}
    strategy:
      matrix: 
        file: ${{ fromJSON(needs.set-matrix.outputs.dotconfig) }}
    steps:

    - uses: actions/checkout@v3

    - name: carry out
      run: python3 extra-files/refresh.py

    - uses: actions/upload-artifact@v3
      with:
        name: ${{ env.DEPLOYDIR }}
        path: ${{ env.DEPLOYDIR }}

  commit:
    needs: refresh
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v3

    - uses: actions/download-artifact@v3
      
    - uses: geekyeggo/delete-artifact@v2
      with:
          name: '*'

    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: refresh .config files 
        commit_author: github-actions[bot] <github-actions[bot]@users.noreply.github.com>
